os:
  - Visual Studio 2017  
install:
  - cinst --allow-empty-checksums -y mingw make
  - refreshenv
build_script:
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - mkdir build
  - mkdir bin
  - cd build
  - cmake --version
  - cmake ..
test_script:
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - make test
