os:
  - Visual Studio 2017  
install:
  - cinst --allow-empty-checksums -y mingw make
  - refreshenv
build_script:
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - mkdir build
  - mkdir bin
  - cmake --version
  - cmake . -G "MinGW Makefiles"
test_script:
  - make
  - make test
